export const GET_USERS = "GET_USERS";
export const SET_LOADING = "SET_LOADING";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const FILTER_USERS = "FILTER_USERS";
export const CLEAR_FILTERED_SEARCH = "CLEAR_FILTERED_SEARCH";
export const CLEAR_USERS = "CLEAR_USERS";
export const USER_NAME_SEARCH = "USER_NAME_SEARCH";
